### ISSUE TITLE
Low level vulnerabilities cause test failures when level is set to moderate

### ISSUE THREAD

**Issue by leeroyrose** [xeroxinteractive/jest-package-audit#348]
When running:

<pre>
await expect({
    level: 'moderate',
    dependencyType: 'dependencies',
}).toPassPackageAudit();
</pre>

Low level vulnerabilities are still causing the test to fail. I debugged it and found that it's failing because of this line of code: https://github.com/xeroxinteractive/jest-package-audit/blob/next/source/index.ts#L81. Low level packages are being marked as vulnerable, if they are not in the allow list, and the pass flag is being set to false.

I think we can get around this by adding a check for successful exit codes before we do the regex table loop. This should also speed things up if there are no vulnerabilities. We then need to determine the vulnerability level for the package being checked and add an additional if statement before setting the pass flag to false.

Looking forward to hearing your thoughts on this!

**Comment by AndrewLeedham** [comment]
Strange, low level vulnerabilities shouldn't be in the output at all, since `yarn`/`npm` should be filtering them out before they get to this code. Can you share the options you are passing to see this?

The exit codes definitely need sorting out at some point, and checking them before parsing the output sounds like a great optimisation :)

**Comment by leeroyrose** [comment]
<img width="825" alt="Screenshot 2020-07-02 at 12 52 38" src="https://user-images.githubusercontent.com/3706842/86355996-72153c80-bc63-11ea-8696-e9f8d5327200.png">

Looks like the flag just determines when to change the exit code rather than filtering the table - taken from the NPM docs:

> By default, the audit command will exit with a non-zero code if any vulnerability is found. It may be useful in CI environments to include the --audit-level parameter to specify the minimum vulnerability level that will cause the command to fail. This option does not filter the report output, it simply changes the command’s failure threshold.

**Comment by AndrewLeedham** [comment]
Ah I see, another difference between `yarn` and `npm`, Yarn docs:
> Applying the level flag will limit the audit table to vulnerabilities of the corresponding level and above. It will not affect the exit code of the command.

Thinking about the exit code suggestion, that would not work because we would not have a list of the relevant vulnerabilities to output in the jest failure.

**Comment by leeroyrose** [comment]
If only they were consistent!

Hmm yeah, good point. I was thinking of just having a short circuit for those 100% pass situations. I.e 0 vulnerabilities, ignoring what's in allow etc, then performing the rest of the real work after that.

**Comment by AndrewLeedham** [comment]
Ah I see yeah exit code 0 short-circuit is fine. I guess to resolve the npm level issue we would need to parse the level from the table and filter it out manually

**Comment by leeroyrose** [comment]
Yep, I wonder if we could parse the entire table rather than picking out just the package name? Having the rest of the data in an object might come in handy for other things.

**Comment by AndrewLeedham** [comment]
Yeah having the whole object could tie in with https://github.com/xeroxinteractive/jest-package-audit/issues/347#issuecomment-652961109

**Comment by leeroyrose** [comment]
Yep. Great suggestion on the allow callback 👌
