### ISSUE TITLE
@pnpm/audit installed incorrectly

### ISSUE THREAD

**Issue by phawxby** [xeroxinteractive/jest-package-audit#670]
https://github.com/xeroxinteractive/jest-package-audit/blob/1ea4f531a13332ca831c28f9cc188f5260a09a31/package.json#L70

It should be a dependency not a development dependency

**Comment by AndrewLeedham** [comment]
@phawxby I still see it is a `devDep` in next and release. Did you change your mind?

**Comment by phawxby** [comment]
Yes. The issue was because the published package typings reference a library which is a devDep and not a dep  so I was getting build errors. I eventually realised that was because I module checking was enabled in the tsconfig.

**Comment by AndrewLeedham** [comment]
We should probably include it as a full dep then. I assume you are talking about the `skipLibCheck` option, which we should be compatible with.
